import { notFound } from "next/navigation";
import type { Metadata } from "next";
import Link from "next/link";
import { Navbar } from "@/components/shared/Navbar";
import { SavingsHero } from "@/components/results/SavingsHero";
import { OptimizationScore } from "@/components/results/OptimizationScore";
import { RecommendationCard } from "@/components/results/RecommendationCard";
import { ToolBreakdownCard } from "@/components/results/ToolBreakdownCard";
import { getAuditBySlug } from "@/lib/db/audits";
import type { AuditResult } from "@/lib/audit/types";
import { formatMonthly } from "@/lib/formatters/currency";

interface PublicAuditPageProps {
  params: Promise<{ slug: string }>;
}

export async function generateMetadata({ params }: PublicAuditPageProps): Promise<Metadata> {
  const resolvedParams = await params;
  const auditRow = await getAuditBySlug(resolvedParams.slug);

  if (!auditRow) {
    return { title: "Audit Not Found - SpendScope" };
  }

  const title = "SpendScope AI Spend Audit";
  const description = `Potential Savings: ${formatMonthly(auditRow.total_monthly_savings)}/mo. Optimization Score: ${auditRow.optimization_score}/100.`;

  return {
    title,
    description,
    openGraph: {
      title,
      description,
      siteName: "SpendScope",
      type: "website",
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
    },
  };
}

export default async function PublicAuditPage({ params }: PublicAuditPageProps) {
  const resolvedParams = await params;
  const auditRow = await getAuditBySlug(resolvedParams.slug);

  if (!auditRow) {
    notFound();
  }

  // Cast JSON to AuditResult since we stringified the whole object
  const result = auditRow.tools_json as unknown as AuditResult;

  return (
    <>
      <Navbar />
      <main>
        {/* ── Hero ── */}
        <SavingsHero result={result} />

        {/* ── Body ── */}
        <div className="mx-auto max-w-4xl px-5 sm:px-8 py-10 sm:py-14 space-y-10">

          {/* Score + AI Summary */}
          <OptimizationScore
            score={result.optimizationScore}
            engineSummary={result.summary}
            aiSummary={auditRow.ai_summary ? { summary: auditRow.ai_summary, source: "ai", generatedAt: auditRow.created_at } : null}
            isLoadingAi={false}
          />

          {/* Recommendations */}
          {result.recommendations.length > 0 && (
            <section aria-labelledby="rec-heading">
              <div className="mb-5 flex items-center justify-between">
                <h2
                  id="rec-heading"
                  className="text-[1.1rem] font-extrabold tracking-tight text-foreground"
                >
                  Recommendations
                  <span className="ml-2 rounded-full bg-muted px-2.5 py-0.5 text-[11px] font-semibold text-muted-foreground">
                    {result.recommendations.filter((r) => r.type !== "already-optimized").length || 1}
                  </span>
                </h2>
              </div>
              <div className="flex flex-col gap-4">
                {result.recommendations.map((rec, i) => (
                  <RecommendationCard key={rec.id} rec={rec} index={i} />
                ))}
              </div>
            </section>
          )}

          {/* Tool Breakdown */}
          {result.toolBreakdowns.length > 0 && (
            <section aria-labelledby="tools-heading">
              <h2
                id="tools-heading"
                className="text-[1.1rem] font-extrabold tracking-tight text-foreground mb-5"
              >
                Tool Breakdown
              </h2>
              <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                {result.toolBreakdowns.map((bd) => (
                  <ToolBreakdownCard key={`${bd.toolId}-${bd.planId}`} breakdown={bd} />
                ))}
              </div>
            </section>
          )}

          {/* CTA / Branding Footer */}
          <div className="mt-12 rounded-2xl bg-muted/50 border border-border p-8 text-center">
            <div className="mb-4">
              <span className="text-[11px] font-bold uppercase tracking-wider text-muted-foreground">
                Generated by SpendScope
              </span>
            </div>
            <h3 className="text-lg font-bold text-foreground mb-2">
              Audit your own AI stack in 60 seconds
            </h3>
            <p className="text-sm text-muted-foreground mb-6 max-w-sm mx-auto">
              Find out where you&apos;re overpaying for AI tooling and duplicate coverage without giving up your email.
            </p>
            <Link href="/audit" className="btn-primary">
              Start free audit
            </Link>
          </div>
        </div>
      </main>
    </>
  );
}
