import { Search, BarChart3, Share2, ShieldCheck, Clock, Sparkles } from "lucide-react";

const FEATURES = [
  {
    id: "instant-audit",
    icon: Search,
    title: "Instant AI Spend Audit",
    description: "Enter your team size and tools. Get a full cost breakdown in under 60 seconds — no spreadsheets, no consultants.",
    iconBg: "rgba(232,93,74,0.10)",
    iconColor: "#E85D4A",
  },
  {
    id: "real-savings",
    icon: BarChart3,
    title: "Real Savings Opportunities",
    description: "See which tools you're overpaying for, where you have duplicate coverage, and how to right-size your stack.",
    iconBg: "rgba(232,93,74,0.10)",
    iconColor: "#E85D4A",
  },
  {
    id: "shareable",
    icon: Share2,
    title: "Shareable Audit Reports",
    description: "Get a unique URL to share with your team or CFO. No login required — just a permanent link to your results.",
    iconBg: "rgba(232,93,74,0.10)",
    iconColor: "#E85D4A",
  },
  {
    id: "no-bias",
    icon: ShieldCheck,
    title: "Zero Vendor Bias",
    description: "No referral fees. No kickbacks. Recommendations are based purely on your usage data and verified public pricing.",
    iconBg: "rgba(232,93,74,0.10)",
    iconColor: "#E85D4A",
  },
  {
    id: "quick-setup",
    icon: Clock,
    title: "No Setup Required",
    description: "No OAuth, no integrations, no API keys. Just tell us what you use and how many people are on your team.",
    iconBg: "rgba(232,93,74,0.10)",
    iconColor: "#E85D4A",
  },
  {
    id: "ai-insights",
    icon: Sparkles,
    title: "AI-Powered Insights",
    description: "Get a plain-English summary of your findings, generated by Claude, with actionable next steps for your stack.",
    iconBg: "rgba(232,93,74,0.10)",
    iconColor: "#E85D4A",
    comingSoon: true,
  },
] as const;

export function Features() {
  return (
    <section
      id="features"
      className="bg-coral py-20 px-5 sm:py-28"
      aria-label="Features"
    >
      <div className="mx-auto max-w-6xl">

        {/* Section header — white on coral */}
        <div className="mx-auto max-w-xl text-center mb-14">
          <p className="section-label justify-center mb-3">
            <span>★</span> Why SpendScope
          </p>
          <h2 className="text-[2rem] font-extrabold tracking-[-0.03em] leading-[1.12] text-white sm:text-[2.75rem]">
            Everything you need to audit smarter
          </h2>
          <p className="mt-4 text-[1rem] text-white/75 leading-relaxed font-medium">
            Built for founders and engineering leads tired of guessing what their AI stack actually costs.
          </p>
        </div>

        {/* Feature grid — white cards on coral (Voi pattern) */}
        <div className="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-3">
          {FEATURES.map((f) => {
            const Icon = f.icon;
            return (
              <div
                key={f.id}
                id={`feature-${f.id}`}
                className="card-white group p-7"
              >
                <div
                  className="mb-5 flex h-11 w-11 items-center justify-center rounded-2xl"
                  style={{ backgroundColor: f.iconBg }}
                >
                  <Icon className="h-5 w-5" style={{ color: f.iconColor }} strokeWidth={1.75} />
                </div>

                <div className="mb-2 flex items-center gap-2">
                  <h3 className="text-[1rem] font-bold tracking-tight text-foreground">
                    {f.title}
                  </h3>
                  {"comingSoon" in f && f.comingSoon && (
                    <span className="rounded-full bg-primary/10 px-2 py-0.5 text-[10px] font-bold uppercase tracking-wider text-primary">
                      Soon
                    </span>
                  )}
                </div>

                <p className="text-sm text-muted-foreground leading-relaxed">
                  {f.description}
                </p>
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}
