import { Search, BarChart3, Share2, ShieldCheck, Clock, Sparkles } from "lucide-react";

const FEATURES = [
  {
    id: "instant-audit",
    icon: Search,
    title: "Instant AI Spend Audit",
    description:
      "Enter your team size and tools. Get a full cost breakdown in under 60 seconds — no spreadsheets, no consultants.",
    iconColor: "#4f46e5",
    iconBg: "rgba(79,70,229,0.08)",
  },
  {
    id: "real-savings-data",
    icon: BarChart3,
    title: "Real Savings Opportunities",
    description:
      "See which tools you're overpaying for, where you have duplicate coverage, and how much you can save by right-sizing.",
    iconColor: "#7c3aed",
    iconBg: "rgba(124,58,237,0.08)",
  },
  {
    id: "shareable-results",
    icon: Share2,
    title: "Shareable Audit Reports",
    description:
      "Get a unique audit URL to share with your team or CFO. No login required — just a permanent link to your results.",
    iconColor: "#059669",
    iconBg: "rgba(5,150,105,0.08)",
  },
  {
    id: "no-bias",
    icon: ShieldCheck,
    title: "Zero Vendor Bias",
    description:
      "No referral fees. No kickbacks. Recommendations are based purely on your usage data and verified public pricing.",
    iconColor: "#d97706",
    iconBg: "rgba(217,119,6,0.08)",
  },
  {
    id: "quick-setup",
    icon: Clock,
    title: "No Setup Required",
    description:
      "No OAuth, no integrations, no API keys. Just tell us what you use and how many people are on your team.",
    iconColor: "#dc2626",
    iconBg: "rgba(220,38,38,0.08)",
  },
  {
    id: "ai-summary",
    icon: Sparkles,
    title: "AI-Powered Insights",
    description:
      "Get a plain-English summary of your findings, generated by Claude, with actionable next steps for your stack.",
    iconColor: "#0891b2",
    iconBg: "rgba(8,145,178,0.08)",
    comingSoon: true,
  },
] as const;

export function Features() {
  return (
    <section
      id="features"
      className="py-24 px-5 sm:py-32"
      aria-label="Features"
    >
      <div className="mx-auto max-w-6xl">

        {/* Section header */}
        <div className="mx-auto max-w-xl text-center mb-16">
          <p className="section-label mb-3">
            <span>★</span> Why SpendScope
          </p>
          <h2 className="text-[2rem] font-extrabold tracking-[-0.025em] leading-[1.15] text-foreground sm:text-[2.5rem]">
            Everything you need to{" "}
            <span className="gradient-text">audit smarter</span>
          </h2>
          <p className="mt-4 text-base text-muted-foreground leading-relaxed">
            Built for startup founders and engineering leaders who are tired
            of guessing what their AI stack actually costs.
          </p>
        </div>

        {/* Feature grid */}
        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {FEATURES.map((feature, i) => (
            <FeatureCard key={feature.id} feature={feature} index={i} />
          ))}
        </div>
      </div>
    </section>
  );
}

type FeatureItem = (typeof FEATURES)[number];

function FeatureCard({ feature, index }: { feature: FeatureItem; index: number }) {
  const Icon = feature.icon;

  return (
    <div
      id={`feature-${feature.id}`}
      className="card-enterprise group relative flex flex-col rounded-xl border border-border bg-card p-6"
      style={{ animationDelay: `${index * 60}ms` }}
    >
      {/* Icon */}
      <div
        className="mb-5 flex h-10 w-10 items-center justify-center rounded-lg"
        style={{ backgroundColor: feature.iconBg }}
      >
        <Icon
          className="h-5 w-5 flex-shrink-0"
          style={{ color: feature.iconColor }}
          aria-hidden="true"
          strokeWidth={1.75}
        />
      </div>

      {/* Title */}
      <div className="mb-2 flex items-center gap-2">
        <h3 className="text-[15px] font-semibold tracking-[-0.01em] text-foreground">
          {feature.title}
        </h3>
        {"comingSoon" in feature && feature.comingSoon && (
          <span
            className="rounded-full px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wider"
            style={{ background: "rgba(79,70,229,0.1)", color: "#4f46e5" }}
          >
            Soon
          </span>
        )}
      </div>

      {/* Description */}
      <p className="text-sm text-muted-foreground leading-[1.65]">
        {feature.description}
      </p>

      {/* Hover accent line */}
      <div
        className="absolute bottom-0 left-6 right-6 h-[1px] scale-x-0 rounded-full opacity-0 group-hover:scale-x-100 group-hover:opacity-100 transition-all duration-300"
        style={{ background: `linear-gradient(90deg, transparent, ${feature.iconColor}40, transparent)` }}
        aria-hidden="true"
      />
    </div>
  );
}
