import { Search, BarChart3, Share2, ShieldCheck, Clock, Sparkles } from "lucide-react";

const FEATURES = [
  {
    id: "instant-audit",
    icon: Search,
    title: "Instant AI Spend Audit",
    description: "Enter your team size and tools. Get a full cost breakdown in under 60 seconds — no spreadsheets, no consultants.",
  },
  {
    id: "real-savings",
    icon: BarChart3,
    title: "Real Savings Opportunities",
    description: "See which tools you're overpaying for, where you have duplicate coverage, and how to right-size your stack.",
  },
  {
    id: "shareable",
    icon: Share2,
    title: "Shareable Audit Reports",
    description: "Get a unique URL to share with your team or CFO. No login required — just a permanent link to your results.",
  },
  {
    id: "no-bias",
    icon: ShieldCheck,
    title: "Zero Vendor Bias",
    description: "No referral fees. No kickbacks. Recommendations are based purely on your usage data and verified public pricing.",
  },
  {
    id: "quick-setup",
    icon: Clock,
    title: "No Setup Required",
    description: "No OAuth, no integrations, no API keys. Just tell us what you use and how many people are on your team.",
  },
  {
    id: "ai-insights",
    icon: Sparkles,
    title: "AI-Powered Insights",
    description: "Get a plain-English summary of your findings, generated by Claude, with actionable next steps for your stack.",
    comingSoon: true,
  },
] as const;

export function Features() {
  return (
    <section
      id="features"
      className="marketing-dot-bg py-16 px-5 sm:py-24 border-b border-border"
      aria-label="Features section"
    >
      <div className="mx-auto max-w-6xl">
        {/* Section Header */}
        <div className="mx-auto max-w-2xl text-center mb-12 sm:mb-16">
          <p className="section-label justify-center mb-3">
            Why SpendScope
          </p>
          <h2 className="text-3xl font-bold tracking-tight text-foreground sm:text-4xl lg:text-5xl">
            Everything you need to audit smarter
          </h2>
          <p className="mt-4 text-base text-muted-foreground leading-relaxed font-medium">
            Built for founders and engineering leads tired of guessing what their AI
            stack actually costs.
          </p>
        </div>

        {/* Feature Grid */}
        <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
          {FEATURES.map((feature) => {
            const Icon = feature.icon;
            return (
              <div
                key={feature.id}
                id={`feature-${feature.id}`}
                className="card group p-6"
              >
                {/* Icon */}
                <div className="mb-4 flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10">
                  <Icon
                    className="h-5 w-5 text-primary"
                    strokeWidth={1.75}
                    aria-hidden="true"
                  />
                </div>

                {/* Title & Badge */}
                <div className="mb-3 flex items-center gap-2">
                  <h3 className="text-sm font-bold tracking-tight text-foreground">
                    {feature.title}
                  </h3>
                  {"comingSoon" in feature && feature.comingSoon && (
                    <span className="rounded-full bg-muted px-1.5 py-0.5 text-2xs font-bold uppercase tracking-widest text-muted-foreground">
                      Soon
                    </span>
                  )}
                </div>

                {/* Description */}
                <p className="text-sm leading-relaxed text-muted-foreground">
                  {feature.description}
                </p>
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}
